"""Cosmos-block action expert for FastWAM MoT coupling.

Mirrors the original FastWAM ActionDiT idea (a transformer over action tokens that
joint-attends with the video DiT), but its blocks ARE Cosmos ``Block``s (same
n_heads=16, head_dim=128, AdaLN, RoPE) so the MoT joint self-attention can concat
K/V across the video and action streams.

Per the chosen design (full-size action DiT), the blocks are initialised by
**copying the Cosmos video DiT blocks** (a warm start from the world model's
dynamics — the analogue of the original interp-init, but exact since the dims
match). Only the action input encoder, output head, timestep embedder and a
(1-D over action steps) RoPE are action-specific.

Action tokens are a length-``Ta`` sequence (one token per action step), embedded
to D=model_channels. Their RoPE is generated by reusing the video net's 3-D RoPE
embedder on a ``[Ta, 1, 1]`` grid (only the temporal axis varies).
"""
from __future__ import annotations

import copy
from typing import Optional

import torch
import torch.nn as nn
from einops import rearrange

from fastwam.utils.logging_config import get_logger

logger = get_logger(__name__)


class CosmosActionExpert(nn.Module):
    def __init__(
        self,
        action_dim: int,
        model_channels: int,
        num_blocks: int,
        num_heads: int,
        crossattn_emb_channels: int = 1024,
        use_adaln_lora: bool = True,
        adaln_lora_dim: int = 256,
    ):
        super().__init__()
        from cosmos_predict2._src.predict2.networks.minimal_v4_dit import (
            Block,
            TimestepEmbedding,
            Timesteps,
        )

        self.action_dim = int(action_dim)
        self.model_channels = int(model_channels)
        self.num_heads = int(num_heads)

        # action-step token embed / un-embed (the only "new" weights besides AdaLN heads)
        self.action_encoder = nn.Linear(action_dim, model_channels)
        self.head = nn.Linear(model_channels, action_dim)

        # timestep embedding for the action diffusion (own copy; same shape as video)
        self.t_embedder = nn.Sequential(
            Timesteps(model_channels),
            TimestepEmbedding(model_channels, model_channels, use_adaln_lora=use_adaln_lora),
        )
        self.t_embedding_norm = nn.RMSNorm(model_channels, eps=1e-6) if hasattr(nn, "RMSNorm") else nn.LayerNorm(model_channels)

        self.blocks = nn.ModuleList(
            Block(
                x_dim=model_channels,
                context_dim=crossattn_emb_channels,
                num_heads=num_heads,
                mlp_ratio=4.0,
                use_adaln_lora=use_adaln_lora,
                adaln_lora_dim=adaln_lora_dim,
                backend="torch",
            )
            for _ in range(num_blocks)
        )

    @torch.no_grad()
    def copy_init_from_video(self, video_net):
        """Warm-start: copy the Cosmos video DiT's transformer blocks + t_embedder."""
        for ab, vb in zip(self.blocks, video_net.blocks):
            ab.load_state_dict(vb.state_dict(), strict=False)
        try:
            self.t_embedder.load_state_dict(video_net.t_embedder.state_dict(), strict=False)
            self.t_embedding_norm.load_state_dict(video_net.t_embedding_norm.state_dict(), strict=False)
        except Exception as e:  # shapes should match, but don't hard-fail the warm start
            logger.warning("action t_embedder warm-start skipped: %s", e)
        logger.info("CosmosActionExpert: copy-initialised %d blocks from video DiT.", len(self.blocks))

    def action_rope(self, video_net, Ta: int, device, dtype):
        """Reuse the video net's 3-D RoPE on a [Ta,1,1] grid -> action-step RoPE."""
        probe = torch.zeros(1, Ta, 1, 1, self.model_channels, device=device, dtype=dtype)
        return video_net.pos_embedder.generate_embeddings(probe.shape, fps=None)

    def prepare(self, noisy_action_B_Ta_a, timesteps_B, crossattn_emb, video_net):
        """Embed action tokens + timestep emb + RoPE; return MoT stream state.

        noisy_action: [B, Ta, action_dim]; timesteps: [B] or [B,Ta]; crossattn: text.
        """
        B, Ta, _ = noisy_action_B_Ta_a.shape
        tokens = self.action_encoder(noisy_action_B_Ta_a)  # [B, Ta, D]
        ts = timesteps_B
        if ts.ndim == 1:
            ts = ts.unsqueeze(1).expand(B, Ta)  # per-token time (same value)
        t_emb, adaln_lora = self.t_embedder(ts)
        t_emb = self.t_embedding_norm(t_emb)
        rope = self.action_rope(video_net, Ta, tokens.device, tokens.dtype)
        return {
            "tokens": tokens,
            "rope": rope,
            "t_emb": t_emb,
            "adaln_lora": adaln_lora,
            "crossattn": crossattn_emb,
            "THW": (Ta, 1, 1),
        }

    def finalize(self, tokens_B_Ta_D):
        """Action tokens -> predicted velocity [B, Ta, action_dim]."""
        return self.head(tokens_B_Ta_D)
